-- 시군구별 이동자수: REGION_MOVERS
CREATE OR REPLACE TABLE DE6_PROJECT_II.RAW_DATA.REGION_MOVERS(
REGION	VARCHAR(100),
WRTTIME	VARCHAR(12),
TOTAL_INMIG	NUMBER(12),
TOTAL_OUTMIG	NUMBER(12),
NETMIG	NUMBER(12),
WITH_PROVI_MIG_WITH_RIGEN	NUMBER(12),
WITH_PROVI_MIG_BTW_MUNI_INMIG	NUMBER(12),
WITH_PROVI_MIG_BTW_MUNI_OUTMIG	NUMBER(12),
INTER_PROV_INMIG	NUMBER(12),
INTER_PROV_OUTMIG	NUMBER(12));

-- 시군구별 이동자수 COPY
COPY INTO DE6_PROJECT_II.RAW_DATA.REGION_MOVERS
FROM 's3://vacant-house-data/APIdata/population_movement.csv'
CREDENTIALS=(AWS_KEY_ID='AWS_KEY_ID' AWS_SECRET_KEY='AWS_SECRET_KEY')
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' ENCODING='EUC-KR');