-- VIEW_SENTIMENT 생성 쿼리 
CREATE OR REPLACE TABLE DE6_PROJECT_II.ANALYTICS.VIEW_SENTIMENT AS
SELECT LEFT(WRTTIME_IDTFR_ID,4) YEAR,
       RIGHT(WRTTIME_IDTFR_ID,2) MONTH,
       TO_DATE(WRTTIME_IDTFR_ID,'YYYYMM') DATE,
       CLS_ID REGION_ID,
       CLS_NM REGION_NM,
       DTA_VAL SENTIMENT_SCORE
FROM DE6_PROJECT_II.RAW_DATA.T235013129634707 
WHERE CLS_ID NOT IN ('50003'/*수도권>소계*/, --통계행 제거
                     '50009'/*비수도권>소계*/,
                     '50006'/*전국>소계*/,
                     '50008'/*비수도권*/);